### ISSUE TITLE
Frozen Bubble: program starts with broken "X"-icon in taskbar and when pinned, doesnt start from the pinned icon

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#90] opened 2017-04-14 15:39 UTC
i know its really silly, but i'd just like to understand whats the cause for this particular program and if i could fix this via desktop file or other method in netrunner, which ships it default.

**Comment by eikehein** [comment] 2017-04-20 09:29
I'll have a look (goes google what Frozen Bubble is ...)

**Comment by eikehein** [comment] 2017-04-20 09:35
Root cause: The program has very broken window data:

WM_CLASS(STRING) = "perl", "perl"

The WM_CLASS is something that doesn't match either its .desktop file name, menu name or executable name.

Further, its command line also doesn't help, since it doesn't use "frozen-bubble" with a shebang, but wraps in /usr/bin/perl:

[eike@ehl1 ~/devel/src/kde/workspace/plasma-desktop/applets/taskmanager (master) 36K]$ ps aux | grep frozen
eike      5320 37.4  1.3 836584 106620 ?       Sl   18:31   1:06 /usr/bin/perl /usr/bin/frozen-bubble

Even though Exec= in the .desktop file is "frozen-bubble".

There would be ways to work around this via taskmanagerrulesrc I think, if you think it's needed.

**Comment by star-buck** [comment] 2017-04-20 09:37
Since its quite popular and shipped default, that would be nice.

**Comment by eikehein** [comment] 2017-04-20 09:51
I'm actually going to write a libtaskmanager patch for this, I want to handle it in a more generic way rather than go app-specific (we always prefer this way).

**Comment by eikehein** [comment] 2017-04-20 10:33
Patch up for review:

https://phabricator.kde.org/D5522

This fixes Frozen Bubble and potentially other perl-SDL apps.

**Comment by eikehein** [comment] 2017-04-24 09:48
Merged: https://commits.kde.org/plasma-workspace/1c8a46791c4eda644920fd0b6abb6197aac423ce

This will be in Plasma 5.10, to be released May 30th

**Closed as completed** 2017-12-13 20:03 UTC
Labels: ready for QA
