### ISSUE TITLE
Discover: after installing, "install" changes to "remove", but wasnt there also an option to "start/launch"?

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#207] opened 2019-10-28 00:04 UTC
i recall after installation there was a convenient way to start any installed app, that seems missing now

**Comment by aleixpol** [comment] 2019-10-28 12:30
Yes, there is. It should show for every application that is launchable, even some KNS resources.

Where do you miss it? Any application that can show me the issue?

**Comment by star-buck** [comment] 2019-10-28 15:20
I installed gltron, but couldnt launch it, just remove.

**Comment by aleixpol** [comment] 2019-10-28 16:11
Right, same issue as https://github.com/blue-systems/plasma-5.17/issues/206 then :/

**Comment by Pointedstick** [comment] 2019-10-28 17:16
Yep duplicate of https://github.com/blue-systems/plasma-5.17/issues/206. Let's continue the discussion there.

**Closed as completed by Pointedstick** 2019-10-28 17:16 UTC
Labels: seen on maui/netrunner
