### ISSUE TITLE
provide proper shadow support for CSD/GTK3

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#131] opened 2018-03-12 08:03 UTC

**Comment by kbroulik** [comment] 2018-03-27 10:20
I think on X this is a lost cause.

There is no way to tell a GTK client-side decorated window apart from a regular window that wants no borders shown. There is a window property `GTK_FRAME_EXTENTS` that tells the compositor how much shadow there is around the window. KWin uses this property to determin whether to force SSD on the window.

However, nowadays this property is only set when the compositor announces support for this property at which case GTK starts rendering its own decoration and KWin is in no position to support that property and X11 KWin is feature frozen anyway.

On Wayland we have a proper negotation protocol and this should just work.

**Comment by davidedmundson** [comment] 2019-01-16 15:47
Dupe of #157

**Closed as completed by davidedmundson** 2019-01-16 15:47 UTC
Labels: suggestion/optimization
