### ISSUE TITLE
taskbar: some programs (like gnome maps) show two consecutive "tasks" (one launcher feedback and later one real task) when starting

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#84] opened 2017-04-13 14:08 UTC
ideally, opening an app should not yield 2 consecutive, visually perceived "tasks", so maybe its due to maps showing the right symbol while loading, but then a second task appears again for the final app, which has the broken logo: 
https://www.dropbox.com/s/ycsgc8nwm2bjksv/gnome-maps.mkv?dl=0

![gnome-maps-missing-icon](https://cloud.githubusercontent.com/assets/840070/25008239/6fa11cc0-2063-11e7-8ad9-c68014eb107a.png)

**Comment by star-buck** [comment] 2017-04-13 15:19
maybe its due to it showing the right symbol while loading, but then a second task appears again for the final app, which has the broken logo. ideally, opening an app should not yield 2 tasks, as its confusing and settle on the first one, which have already the correct logo.

**Comment by star-buck** [comment] 2017-04-13 15:22
capture:
https://www.dropbox.com/s/ycsgc8nwm2bjksv/gnome-maps.mkv?dl=0

**Comment by star-buck** [comment] 2017-04-13 15:32
some more apps tested:
- frozen bubble also opens a second "task" called "frozen bubble 2" with missing icon
- tron opens one task and icon just fine
- lollipop opens in one swift task with icon
- gnome software opens two tasks, but at least has icon
https://www.dropbox.com/s/y2ev14ntj8m0nqd/tm-various.mkv?dl=0

**Comment by star-buck** [comment] 2017-04-13 15:41
some more examination:
pinning Frozen Bubble with broken icon does pin the broken icon, but cannot start the program afterwards.
Adding a pinned icon from menu works with pengiun icon and starts, but still revokes the broken icon.

**Comment by star-buck** [comment] 2017-04-13 15:50
PS. frozen bubble seems to really change its window name to Frozen Bubble 2!

**Comment by eikehein** [comment] 2017-04-13 21:41
To clear up the confusion: There is never actually two tasks.

What happens is this:
1. App is launched from a launcher, this generates a startup notification based on menu data, the Task Manager shows a startup notification
2. App opens a window, this shows on the Task Manager

Now, when the Task Manager is able to figure out that the startup notification and the window belong to the same app, it will hide the startup notification button at the same time it starts showing the window button, for a seamless hand-off.

When it cannot do this, they continue to co-exist, until the startup notification times out and disappears.

Figuring out what app a window belongs to on X11 is a monumental task. We have a carefully tuned, decade-groomed, recently much refreshed and renovated (in the libtm rewrite) heuristic for it that is pages and pages of code long, and tries to pull every trick in the book, along with the long, long list of ways that application developers fuck up setting the correct window metadata and .desktop file contents.

This heuristic keeps being improved, and we handle more horrible broken apps with every release. Some apps will never work and just need to be fixed by their devs because it's technically impossible to handle them, though.

For debugging each such problem, the following bits of debug data are needed:
- The path to the .desktop file for the app on the system
- The full contents of the .desktop file
- xprop output for the app window
- (Optional but useful) When pinning the app, the launcher URL that was generated from the plasma-org.kde.plasma.desktop-appletsrc file

We handle about 1-4 such cases per release cycle. One tends to result in code improvements and the others are broken apps.

The most recent one, if you remember, was the "System Settings shows two tasks" thing, which was a bug in System Settings which I fixed. But again, the TM already tries to handle all the application bugs it possibly can, this is very liberal code in what it accepts from the app.

I'm 100% confident that we do this better than any other DE on X11 on average and have the most complete code for it (and I have compared, and I know the bugs the others have). That doesn't mean it can't be improved further (it very likely will), but it means that any problem that still exists is probably of the "interesting and strange" variety.

As for XFCE specifically, if I remember correctly, for task buttons it just shows the window icon instead of making any attempt to use the theme/configured menu icon. We make all the attempt we can to use the theme/configured menu icon, in part because that's what you (and other users) specifically requested. Because otherwise, the icon would sometimes change from launcher/notification to task (when the app uses a different icon, different icon theme, different mechanism for loading/scaling the icon, ...) or sometimes just not follow the icon theme and not change when changing the icon theme. The xfce Task Manager is in general very primitive and buggy.

This is a long preface because I don't want another "Plasma sucks, XFce is so much better" thing :). I'm probably the best expert on exactly this area on the planet now and I know there's no free lunches with it.

I'll gladly look at any individual cases and I'm sure the code will see the usual rate of continued improvements, though.

And now sleep/weekend ...

**Comment by eikehein** [comment] 2017-04-13 21:50
I had a very quick look at Gnome Maps, and here's what I found.

The desktop file name: /usr/share/applications/org.gnome.Maps.desktop

There's no StartupWMClass value in the .desktop file.

The WM_CLASS on the window: WM_CLASS(STRING) = "gnome-maps", "Gnome-maps"

This is wrong - the second component WM_CLASS is supposed to be the menu id (we could understand both org.gnome.Maps(.desktop) and Maps) or the value of StartupWMClass in the .desktop file (which is missing).

That's why we can't find the .desktop file for the window and can't load the icon from there, and can't combine the task button with the startup notification button.

I'll see if I can talk to the Gnome people about their stuff ... mapping from Gnome-maps to org.gnome.Maps.desktop on the string level wouldn't really be possible without making the heuristic very fragile.

To show I'm not making this up, see their own docs: https://wiki.gnome.org/Projects/GnomeShell/ApplicationBased

> To ensure the GNOME 3 Shell will track your application, you can also set the WM_CLASS X window property to be the same as your application's .desktop file name, without the .desktop extension (the desktop file should be lower-case).

> The easiest way to achieve this is to have your application's process name match the .desktop file name, and ensure you use g_option_context_parse. 

> [...]

> WM_CLASS(STRING) = "chromium-browser", "Chromium-browser"

> The second item here is the WM_CLASS. Chromium-browser (when lowercased) matches the chromium-browser.desktop as we want. 

Gnome Maps doesn't follow their own docs.

Ok, now really sleep/weekend :)

**Comment by eikehein** [comment] 2017-04-13 21:56
Small addition:

Note it's possible to fix this by adding:

> StartupWMClass=Gnome-maps

to /usr/share/applications/org.gnome.Maps.desktop

This will (or should) even work live at runtime without a Plasma restart.

StartupWMClass is a freedesktop.org standard field.

**Comment by eikehein** [comment] 2017-04-13 22:05
Filed a bug at Gnome: https://bugzilla.gnome.org/show_bug.cgi?id=781293

Should be interesting.

And now I'm really, actually putting the laptop away ;)

**Comment by star-buck** [comment] 2017-04-14 15:28
Thanks for the explanation!

(For simplicity of not mixing two issues, I'll seperate the Frozen Bubble from this, and continue with the two "tasks" visible issue):

I checked with various DEs, so Cinnamon shows only one task (even with the correct Pengiun icon as logo), but then they only have a launcher feedback when clicking on their icon without expanding a real task first, so thats kinda "cheating" (but hey, worked for me).
XFCE does also not show 2 tasks, but has a broken penguin icon in the task like us.

@eikehein : 
With you being the expert on this, maybe we can find a solution drawing from those examples:

- how about an option so that the visual feedback for launchers doesnt expand a "task" right away, but only shows an icon with the spinner feedback and waiting for the real task to come up and then expand to it?
So it would look like starting a pinned IconOnly-task launcher with the spinner on top of the icon, then once the programtask is loaded expand to the full task with text?
The question is would that then be seamlessly working, without simply blending out the initial launcher icon while opening another icon+task next to it?

Will still keep thinking about this more and test other DEs for ideas of course.

**Comment by star-buck** [comment] 2017-04-14 15:46
> This heuristic keeps being improved, and we handle more horrible broken apps with every release. 

Now that's interesting: Do you have a link to the heuristics where all the (broken) apps are added/handled?

**Comment by eikehein** [comment] 2017-04-14 16:34
> Do you have a link to the heuristics where all the (broken) apps are added/handled?

Yep. Most of the code is here:

https://cgit.kde.org/plasma-workspace.git/tree/libtaskmanager/xwindowtasksmodel.cpp

Most notably in the windowUrl method and related methods like servicesFromPid (this is for example a fallback for when windows have no metadata, then we even try to get the command line they were launched with from /proc, to look up the binary name in the .desktop file db).

We also have a system for special fixups in an rc file:

https://cgit.kde.org/plasma-workspace.git/tree/libtaskmanager/taskmanagerrulesrc

We try to keep the bundled special exception rules as small as possible and handle it generically in the C++ code if possible, because maintaining rules is a mess. But the rules support very complex mapping for metadata properties, regex replaces, etc. if necessary. For a while this rules file was 3x as long with complicated mapping rules for Chrome web apps until we found a better approach.

Of the competing desktops, the second most sophisticated at this is Unity. They have a library called "bamf" that contains a lot of similar logic and special rules. In Gnome Shell, the ShellWindowTracker part of the shell codebase also has some similar stuff, although less complete than libtaskmanager or Unity bamf.

It's a huge mess on X11 and hard on everyone. On Wayland it's a lot better because the spec mandates apps need to put a proper .desktop file id on the window as appid property. The problem is that X11 predates .desktop files by decades, so ... anyway even on Wayland app developers can screw it up, but the common case is spec'd better. As a TM dev that's one of the things I'm most excited by about Wayland ;).

> how about an option so that the visual feedback for launchers doesnt expand a "task" right away, but only shows an icon with the spinner feedback and waiting for the real task to come up and then expand to it?

Not a bad idea, we could do that. Basically that's what happens on ITM where everything always stays an icon. In EITM it expands when transitioning to a startup. But I could layout startups to remain icon size and only expand once the window comes - this is possible to adjust (without changes to libtaskmanager even, it's all in the applet UI QML code).

**Comment by eikehein** [comment] 2017-04-14 16:36
^ I'll experiment with this change next week :)

**Comment by star-buck** [comment] 2017-04-14 16:54
> I could layout startups to remain icon size and only expand once the window comes - this is possible to adjust (without changes to libtaskmanager even, it's all in the applet UI QML code).

That would be really awesome if working.

**Comment by eikehein** [comment] 2017-04-18 08:50
Meanwhile gnome.org wrote a patch for Gnome Maps: https://bugzilla.gnome.org/show_bug.cgi?id=781293

**Comment by eikehein** [comment] 2017-04-19 11:09
I implemented your (really good) suggestion for EITM mode, patches under review:

https://phabricator.kde.org/D5505
https://phabricator.kde.org/D5504

It ended up taking a small libtaskmanager patch after all, I realized it was the best way to go for performance and correctness reasons and can also be used to improve some other stuff in the applet.

**Comment by eikehein** [comment] 2017-04-20 11:05
The two patches linked above are now merged and will be in Plasma 5.10.

I don't know if it's appropriate to set this ticket to "ready for QA" as it was about multiple things. Please decide :)

**Comment by eikehein** [comment] 2017-04-21 09:29
Tangentially related, I opened a new thread on the wine-devel mailing list to try and poke them into fixing the problems Plasma/Unity/Gnome/Cinnamon have with wine: https://www.winehq.org/pipermail/wine-devel/2017-April/117413.html

**Closed as completed** 2018-02-07 08:26 UTC
Labels: ready for QA
